<?php COMPONENT::init(COMPONENT::QUANTUM, ARRAY(MODEL_COMPONENT::NAVBAR_STORIES_CAT, MODEL_COMPONENT::ALL_CATEGORIES_UPDATED)); ?>
<?php COMPONENT::init(COMPONENT::QUANTUM, ARRAY(MODEL_COMPONENT::NAVBAR_SPECIAL, MODEL_COMPONENT::ALL_CATEGORIES)); ?>
<?php COMPONENT::init(COMPONENT::QUANTUM, ARRAY(MODEL_COMPONENT::LIST, MODEL_COMPONENT::ALL_PRODUCTS)); ?>