<?php
	CLASS MODEL_COMPONENT {
		//a model component.php
		PUBLIC CONST HEADER_CATEGORY =				'header-category';						
		PUBLIC CONST ADS =							'ads';				
		PUBLIC CONST MASTER =						'master';				
		PUBLIC CONST slave =						'slave';	
		PUBLIC CONST FOOTER =						CONF::SLUG_FOOTER;			
		PUBLIC CONST QUANTUM =						'quantum';
		PUBLIC CONST HEADER =						CONF::SLUG_HEADER;		
		PUBLIC CONST ICON =							'icon';
		PUBLIC CONST MODAL =						'modal';		
		PUBLIC CONST MENU =							'menu';
		PUBLIC CONST PROPERTIES =					'properties';		
		PUBLIC CONST COMMENTS =						'comments';
		PUBLIC CONST COOKIES =						'cookies';				
		PUBLIC CONST SHARE =						'share';
		PUBLIC CONST SIDEBAR =						'sidebar';
		PUBLIC CONST TITLE =						'title';
		PUBLIC CONST CONTENT =						'content';
		
		PUBLIC CONST SHARP = 						0;
		PUBLIC CONST LIST = 						1;	
		PUBLIC CONST CAROUSEL =						2;
		PUBLIC CONST NAVBAR =						3;
		PUBLIC CONST CLOUD =						4;		
		PUBLIC CONST NAVBAR_SPECIAL =				5;
		PUBLIC CONST DEFAULT = 						6;	
		PUBLIC CONST NAVBAR_STORIES_NEWS =			7;
		PUBLIC CONST NAVBAR_STORIES_CAT =			8;
		PUBLIC CONST CAROUSEL_MODAL_C = 			9;	
		PUBLIC CONST LIST_CLOUD = 10;
	
		PUBLIC CONST ALL_CATEGORIES = 				0;
		PUBLIC CONST ALL_PRODUCTS = 				1;
		PUBLIC CONST TOP_PRODUCTS = 				2;
		PUBLIC CONST NEWS = 						3;
		PUBLIC CONST UPDATED = 						4;
		PUBLIC CONST ALL_CATEGORIES_HIDDEN =		5;
		PUBLIC CONST MODAL_NEWS_STORIES 				=		6;//CONF::MODAL_C carouselmodal mejor	
		PUBLIC CONST ALL_CATEGORIES_UPDATED	= 7;
		PUBLIC CONST ALL_PRODUCTS_CLOUD = 8;
	
		PUBLIC CONST MODAL_PRODUCT_DETAIL	=		0;			
		PUBLIC CONST MODAL_SHARE	=				1;			
		PUBLIC CONST MODAL_STORIES	=				2;	
		PUBLIC CONST MODAL_MENU	=					3;	
		PUBLIC CONST MODAL_COOKIES	=				4;	
		
		PUBLIC CONST PROPERTIES_DETAIL	=			0;	
		PUBLIC CONST PROPERTIES_INFO	=			1;	
		PUBLIC CONST PROPERTIES_LINKS	=			2;	
		PUBLIC CONST PROPERTIES_FEATURED	=		3;	
		PUBLIC CONST PROPERTIES_BUTTONREGISTER	=		4;			
		//a model component.php

		PUBLIC CONST H1 = 1;
		PUBLIC CONST H1_BOLD = 2;
		PUBLIC CONST H2 = 3;
		PUBLIC CONST H2_BOLD = 4;	
		PUBLIC CONST H3 = 5;
		PUBLIC CONST H3_BOLD = 6;	
		PUBLIC CONST H4 = 7;
		PUBLIC CONST H4_BOLD = 8;
		PUBLIC CONST H5 = 9;
		PUBLIC CONST H5_BOLD = 10;	
		PUBLIC CONST H6 = 11;
		PUBLIC CONST H6_BOLD = 12;	
		PUBLIC CONST NORMAL = 13;
		PUBLIC CONST NORMAL_BOLD = 14;
		PUBLIC CONST SMALL = 15;
		PUBLIC CONST SMALL_BOLD = 16;
		PUBLIC CONST X_SMALL = 17;	
		PUBLIC CONST X_SMALL_BOLD = 18;
		
		PUBLIC CONST ICON_S = 1;
		PUBLIC CONST ICON_M = 2;
		PUBLIC CONST ICON_L = 4;
		PUBLIC CONST ICON_XL = 7;

		public const CONTENT_EXC = 0;
		PUBLIC CONST CONTENT_CUT = 1;
		PUBLIC CONST CONTENT_FULL  = 2;
	}
?>